### ISSUE TITLE
Kanban Board: workload distribution

### ISSUE THREAD

**Issue by Kingjosh007** [Timowest12/rubycapstone#39]
Here is the [link to the Github project](https://github.com/Timowest12/rubycapstone/projects/1).

**Team Member 1:** @Kingjosh007 (King Josaphat Chewa)
**Team Member 2:** @Timowest12  (Timo Wester)
**Team Member 3:** @phelian23  (Oluwafemi Kolawule)

**Comment by mikethreels** [comment]
Hi Team, 

Good job assigning the cards to the group members 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] there are 3 cards without a description of the task, please make sure to add a description to all the tasks before requesting another code review.
- [ ] The requirements listed as [group tasks](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md#group-task) have a corresponding card in the Kanban board.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kingjosh007** [comment]
Thanks for the quick feedback. Working on it.

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
